#!/bin/bash
set -euxo pipefail

# re-generate all asset files
go run ./cmd/image_gen config.yaml

# run go test to make sure all new code passes
go test ./...

# build the .gba file
tinygo build -o=flappy_boot.gba -target=gameboy-advance -opt=s -gc=leaking .
