OutDir: internal/assets
SetTransparent: "#FFFFFF"
TileSets:
  - Name: player
    File: assets/player.png
    Size: "16x16"
    Description: the sprite sheet for the player character
  - Name: playerAnim
    File: assets/player_anim_ts.png
    Size: "32x16"
    Description: the sprite sheet for the player character and all it's associated animations
  - Name: pillars
    Size: "8x8"
    File: assets/pillar_ts.png
    Description: |
      the tile set for the pillars background, it contains tiles that are not in the default tile map
      which is why it is defined seperately here
  - Name: numbers
    Size: "16x16"
    File: assets/numbers_large_ts.png
    Description: a 16x16 set of digits (0-9)
  - Name: select
    Size: "8x8"
    File: assets/select_ts.png
    Description: a simple spinning select arrow
  - Name: banners
    Size: "32x16"
    File: assets/score_best_ts.png
    Description: score banners for the game over screen
  - Name: logo
    Size: "32x32"
    File: assets/logo_ts.png
    Description: the main logo for flappy boot
  - Name: advance
    Size: "16x16"
    File: assets/advance_ts.png
    Description: the advance badge that goes with the flappy boot logo
  - Name: start
    Size: "16x8"
    File: assets/press_start_ts.png
    Transparent: "#FF00FF"
    Description: the PRESS START text present on the title screen
  - Name: debug
    Size: "8x8"
    File: assets/debug_ts.png
    Description: small tileset useful for debugging
TileMaps:
  - Name: bluebg
    File: assets/blue_bg_ts.png
    Description: a small selection block for when you game over
  - Name: pillars
    File: assets/pillar_tm.png
    TileSet: pillars
    Description: the tile map for the pillars background. It includes both the pillars and grass tiles
  - Name: sky
    File: assets/sky_tm.png
    Transparent: "#FF00FF"
    Description: the furthest background tile map, it contains only the sky
  - Name: clouds
    File: assets/clouds_tm.png
    Description: the background clouds
  - Name: mainmenu
    File: assets/main_menu_tm.png
    Description: the main set for the main menu
